### ISSUE TITLE
Default branches on github are now named "main"

### ISSUE THREAD

**Issue by amychurchwell** [bcanseco/github-contribution-graph-action#5]
'backfill-commits' fails because there is no remote branch 'master' to clone in new repositories:
```
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```

**Comment by amychurchwell** [comment]
Easy fix is an update to docs but perhaps it is worth renaming the branch to main if most folks use this in new repos anyway?

**Comment by bcanseco** [comment]
Thanks for the report, @amychurchwell!

Think this calls for a major version bump. Maybe we can take advantage of [`$GITHUB_REF`](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables) as a default instead of `master` if the user doesn't pass in a `GIT_BRANCH`. That way it'll work for whatever the default branch is.

PRs are welcome, otherwise I'll get to it this weekend 😄
